#!/bin/bash

# Your Puppet server here


PUPPETSERVER='puppet.reallifechurch.org'

TESTURL='https://raw.github.com'

# Test for network conection. Github needs to be up for this to work, so it might as well be that
if curl --output /dev/null --silent --head --fail "$TESTURL"; then
  echo "URL exists: $TESTURL"
else
  exit 1
fi

# Download, install and configure Puppet and Facter
curl -o /tmp/install_puppet.py https://raw.githubusercontent.com/RealLifeChurch/macscripts/master/simian_migration/install_puppet.py; python /tmp/install_puppet.py --serial --server $PUPPETSERVER

sleep 15
# Run Puppet
puppet agent -t --waitforcert 20 --environment macs
sleep 15
/usr/local/macnamer/namer
sleep 15
puppet agent -t
sleep 15
touch /Users/Shared/.com.googlecode.munki.checkandinstallatstartup

#Set Computer Name

# Clean up a little
rm /Library/LaunchDaemons/org.reallifechurch.simian_migrate_bootstrap.plist
rm -Rf /usr/local/simian_migrate

curl -o /Library/Caches/com.apple.desktop.admin.png https://raw.githubusercontent.com/RealLifeChurch/macscripts/master/simian_migration/com.apple.desktop.admin.png
sleep 15

# reboot
reboot
