#!/bin/bash

# Your Puppet server here


PUPPETSERVER='puppet.reallifechurch.org'

TESTURL='https://raw.github.com'

# Test for network conection. Github needs to be up for this to work, so it might as well be that
if curl --output /dev/null --silent --head --fail "$TESTURL"; then
  echo "URL exists: $TESTURL"
else
  exit 1
fi
#if [ ! -f /Users/Shared/.loginwait ]; then
#  curl -o /Library/Caches/com.apple.desktop.admin.png https://raw.githubusercontent.com/RealLifeChurch/macscripts/master/simian_migration/wait.png
#  touch /Users/Shared/.loginwait
#  reboot
#fi
#Delete all profile settings

/usr/bin/profiles -D -f

#Remove key parts of Munki so that simian can install and run

sudo launchctl unload /Library/LaunchDaemons/com.googlecode.munki.*
sudo rm -rf "/Applications/Managed Software Center.app"
sudo rm -f /Library/LaunchDaemons/com.googlecode.munki.*
sudo rm -f /Library/LaunchAgents/com.googlecode.munki.*
sudo rm -Rf "/Library/Managed Installs/Cache"
sudo rm -Rf "/Library/Preferences/ManagedInstalls.plist"
sudo rm -Rf "/Library/Preferences/MunkiReport.plist"
sudo rm -Rf "/usr/local/munki"
sudo pkgutil --forget com.googlecode.munki.admin
sudo pkgutil --forget com.googlecode.munki.app
sudo pkgutil --forget com.googlecode.munki.core
sudo pkgutil --forget com.googlecode.munki.launchd


# Download, install and configure Puppet and Facter
curl -o /tmp/install_puppet.py https://raw.githubusercontent.com/RealLifeChurch/macscripts/master/simian_migration/install_puppet.py; python /tmp/install_puppet.py --serial --server $PUPPETSERVER

# Run Puppet
puppet agent -t --environment macs --waitforcert 20
touch /Users/Shared/.com.googlecode.munki.checkandinstallatstartup

# Clean up a little
rm /Library/LaunchDaemons/org.reallifechurch.simian_migrate_bootstrap.plist
rm -Rf /usr/local/simian_migrate

curl -o /Library/Caches/com.apple.desktop.admin.png https://raw.githubusercontent.com/RealLifeChurch/macscripts/master/simian_migration/com.apple.desktop.admin.png
rm /Users/Shared/.loginwait

# reboot
reboot
